### ISSUE TITLE
Make Submodules Point to eosnetworkfoundation repos rather than eosio

### ISSUE THREAD

**Issue by ClaytonCalabrese** [eosnetworkfoundation/mandel.cdt#1]
### Currently the .gitmodules file points at eosio repositories. This should be changed to point at eosnetworkfoundation forks instead.

This applies to both mandel.cdt, and it's submodule https://github.com/eosnetworkfoundation/cdt-llvm which also points at eosio repos.

**Comment by larryk85** [comment]
Thanks for your contributions.  Please continue to do so as we move this forward.
