### ISSUE TITLE
Fix build issue where variants no longer part of abi struct

### ISSUE THREAD

**Issue by oschwaldp-oci** [eosnetworkfoundation/mandel.cdt#16]
Looks like in a recent commit to remove tools (commit: https://github.com/eosnetworkfoundation/mandel.cdt/commit/a43f6a818e3d5718bb6b33c7fb9b57e41585b9d1) `variants` was removed from the `abi` struct, but not all references to it in `abigen.hpp` causing build to fail.

Reinstating variants as part of abi struct.

**Comment by larryk85** [comment]
@oschwaldp-oci that was my fault.  Can you add back the line std::set<abi_variant> to the ABI struct? And open a different PR?
