### ISSUE TITLE
Add rest of Crypto Extensions

### ISSUE THREAD

**Issue by larryk85** [eosnetworkfoundation/mandel.cdt#31]
As part of 3.0.0-rc1 we added the CRYPTO_PRIMITIVES extension functions to the CAPI and some to the C++ api.  We need to add the rest of these C++ crypto functions as part of a larger set of changes to the core data types and libraries.

**Comment by stephenpdiesel** [comment]
Proposal for this work to be defined in https://github.com/eosnetworkfoundation/mandel.cdt/issues/49

**Comment by ericpassmore** [comment]
closed in AntelopeIO/CDT
