### ISSUE TITLE
Move to non-fork

### ISSUE THREAD

**Issue by jafri** [eosnetworkfoundation/mandel.cdt#37]
Having mandel.cdt as a fork on github prevents searching through the code

**Comment by stephenpdiesel** [comment]
@jafri do you have any tips on how to easily do this without creating a completely new repo?

**Comment by jafri** [comment]
@stephenpdeos You can contact github support (https://github.com/contact) and ask them to switch your repository to "normal mode".

**Comment by stephenpdiesel** [comment]
As of yesterday, this repo is no longer forked
