### ISSUE TITLE
Make varints compile time constructable

### ISSUE THREAD

**Issue by smlu** [eosnetworkfoundation/mandel.cdt#43]
The varints [unsigned_int](https://github.com/eosnetworkfoundation/mandel.cdt/blob/3c5f7777383cef4581000a1f51603b7240ab65a1/libraries/eosiolib/core/eosio/varint.hpp#L22-L237) & [signed_int](https://github.com/eosnetworkfoundation/mandel.cdt/blob/3c5f7777383cef4581000a1f51603b7240ab65a1/libraries/eosiolib/core/eosio/varint.hpp#L246-L464) are just serialization wrappers for type `uint32_t` & `int32_t`. They should be compile time constructable to be available for compile time [constant expressions](https://en.cppreference.com/w/cpp/language/constant_expression).

**Comment by stephenpdiesel** [comment]
Closing since it is now duplicated in https://github.com/AntelopeIO/cdt/issues/13
