### ISSUE TITLE
Slow deserialization for std::vector<unsigned char>

### ISSUE THREAD

**Issue by elmato** [eosnetworkfoundation/mandel.cdt#48]
When deserializing a _std::vector_ of **unsigned char** it will fall into the generic datastream operator for vectors, making the deserialization of a large array too slow

```c++
template<typename Stream, typename T>
datastream<Stream>& operator << ( datastream<Stream>& ds, const std::vector<T>& v ) {
   ds << unsigned_int( v.size() );
   for( const auto& i : v )
      ds << i;
   return ds;
}
```

**Comment by stephenpdiesel** [comment]
Potential candidate for rc3 but not a release blocker

**Comment by linh2931** [comment]
This was fixed by https://github.com/AntelopeIO/cdt/pull/27.
