### ISSUE TITLE
ccache duplicating generation of .obj files

### ISSUE THREAD

**Issue by ClaytonCalabrese** [eosnetworkfoundation/mandel.cdt#7]
Using WSL 2.0 with Ubuntu 20.04, I was attempting to build mandel.cdt.  I repeatedly ran into missing symbol errors, regardless of the version of mandel.cdt I was using. Eventually I narrowed the culprit to ccache, which was taking the first generated .obj file and duplicating it across all other .obj files.

This meant that each .obj file had the same symbols as crypt.obj, meaning symbols such as strlen, memcmp and others were always missing when trying to compile.

I was able to resolve this by disabling ccache using the following command `export CCACHE_DISABLE=1`.  Due to being avoidable, I don't consider this bug to be of any urgency to resolve.

**Comment by larryk85** [comment]
Thanks Clayton, I will add a cmake flag to disable CCACHE entirely.  Or did you want to work on it?

**Comment by larryk85** [comment]
Also, we have a new tool that we are trying to get going called [DUNE](https://github.com/eosnetworkfoundation/DUNE).  Can I ask that you be a guinea pig for that tool?
